############################################ DEFAULT
# 모든 프로파일에 공통으로 적용할 사항은 여기에 기입한다.
spring:
  profiles:
    active: local # default profile을 지정한다.

---
############################################ LOCAL

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8 
      enabled: true 
      force: true
    
spring:
  config:
    activate:
      on-profile: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
       ddl-auto: validate
      
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB

jwt:
  header: Authorization
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK # fill in base64 [command: echo {plain_text} | base64]
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg== # it must be different from the access key secret
  access-token-validity-in-seconds: 300 # 10 min
  refresh-token-validity-in-seconds: 86400 # 24 hour # ??? ?? ?? ? 1?

file:
  path: c:/sts/workspace/com.cbw.security.jwt/src/main/resources/upload/
  
---
############################################ TEST

spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/test # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK # fill in base64 [command: echo {plain_text} | base64]
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg== # it must be different from the access key secret
  access-token-validity-in-seconds: 600 # 10 min
  refresh-token-validity-in-seconds: 86400 # 24 hour # ??? ?? ?? ? 1?

