INSERT INTO ACCOUNT (ACCOUNT_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED, TOKEN_WEIGHT)
VALUES (1, 'admin', '$2a$10$M/wMG36e2Pye82xjBIqAAu651cKo2B2hjKVdCd7CbHM3LYgNKKQTm', 'admin', 1, 1);

INSERT INTO ACCOUNT (ACCOUNT_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED, TOKEN_WEIGHT)
VALUES (2, 'user', '$2a$10$M/wMG36e2Pye82xjBIqAAu651cKo2B2hjKVdCd7CbHM3LYgNKKQTm', 'user', 1, 1);

INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID, AUTHORITY_NAME) values (1, 'ROLE_MEMBER');
INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID, AUTHORITY_NAME) values (2, 'ROLE_MEMBER');